"""
config.py — All hyperparameters and settings for CodeLens Research.
Edit this file to customise model, training, and generation behaviour.
"""
import torch
from dataclasses import dataclass, field


@dataclass
class Config:
    # ── Model ──────────────────────────────────────────────────────────────
    model_name: str = "Salesforce/codet5-base-codexglue-sum-python"
    fallback_model: str = "t5-base"

    # ── Tokenisation ───────────────────────────────────────────────────────
    max_input_length: int = 512    # code tokens fed to encoder
    max_target_length: int = 512   # paper tokens generated by decoder

    # ── Training ───────────────────────────────────────────────────────────
    output_dir: str = "./checkpoints"
    num_train_epochs: int = 5
    per_device_train_batch_size: int = 4
    per_device_eval_batch_size: int = 4
    learning_rate: float = 3e-4
    warmup_steps: int = 200
    weight_decay: float = 0.01
    fp16: bool = torch.cuda.is_available()
    gradient_accumulation_steps: int = 4
    eval_steps: int = 100
    save_steps: int = 100
    load_best_model_at_end: bool = True

    # ── Generation ─────────────────────────────────────────────────────────
    num_beams: int = 5
    no_repeat_ngram_size: int = 3
    length_penalty: float = 1.5
    min_length: int = 100
    max_new_tokens: int = 512
    temperature: float = 0.8

    # ── Paper sections (order matters — controls output order) ─────────────
    sections: list = field(default_factory=lambda: [
        "abstract",
        "introduction",
        "methodology",
        "results",
        "conclusion",
    ])


# Singleton used across modules
CFG = Config()
